### ISSUE TITLE
Sporadic KeyError when using get_multi

### ISSUE THREAD

**Issue by jamesonjlee** [linsomniac/python-memcached#10]
```
# some web code here
# keys = [key, key+'_queued']
 File "./services/cache.py", line 33, in mget
    results = self.get_multi(keys)
  File "/var/www/heydayserver/env/local/lib/python2.7/site-packages/memcache.py", line 972, in get_multi
    retvals[prefixed_to_orig_key[rkey]] = val   # un-prefix returned key.
KeyError: '-34.9832:146.2685_queued'
```

I am not sure why this is happening though, all I use the memcache for is to store json strings with keys.  It happens sporadically, around redeploy of a Flask server.

**Comment by ramnes** [comment]
Just for reference, we had the same problem with uWSGI and gevent greenlets. Adding a ``gevent.monkey.patch_thread()`` before the Client import fixed it. We had uWSGI monkey patch option activated, but here you still need to make it manually. See uWSGI documentation for more explanation.
