### ISSUE TITLE
can't install python-memcached1.58 in Python 3.6.0b2

### ISSUE THREAD

**Issue by sc-syf** [linsomniac/python-memcached#103]
here is the traceback:

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    version=get_module_constant('memcache', '**version**'),
  File "/home/ubuntu/.myvenv/lib/python3.6/site-packages/setuptools/depends.py", line 164, in get_module_constant
    return extract_constant(code, symbol, default)
  File "/home/ubuntu/.myvenv/lib/python3.6/site-packages/setuptools/depends.py", line 195, in extract_constant
    const = code.co_consts[arg]
IndexError: tuple index out of range

**Comment by sscherfke** [comment]
And in 3.6.0b4, too. 

Fedora 24, 64bit

**Comment by timgraham** [comment]
@dieselmachine, the install is faliing at `get_module_constant('memcache', '__version__')` (added in https://github.com/linsomniac/python-memcached/pull/82). Any idea about the cause?

**Comment by dieselmachine** [comment]
I normally don't mess with beta versions of python, but i'll poke around tonight and see what's changed between 3.5.2 (which is working for me) and the betas mentioned above.

**Comment by carl-ellis** [comment]
Looks like the issue is in setuptools and it's still unknown what is causing it (https://github.com/pypa/setuptools/issues/866) . It might be worth reverting back to manual versioning in ```setup.py``` so the library will work in 3.6

**Comment by carl-ellis** [comment]
Oh wow, the setuptools issue has been solved in v32.3.1. That was very quick!

**Comment by sc-syf** [comment]
@carl-ellis , thanks a lot !
It's solved while use 
> pip3 install -U setuptools

to upgrade the setuptools  from 27.1.2 to 32.3.1.

I'll close this issue.
