### ISSUE TITLE
python-memcached in 1.58 encoded question

### ISSUE THREAD

**Issue by sherwinl1u** [linsomniac/python-memcached#104]
By reading the code in memcache.py,  I found a encoded question.
In set() founction, It encode to utf8, if  the value is six.text_type
 def _val_to_store_info(self, val, min_compress_len):
        flags = 0
        if isinstance(val, six.binary_type):
            pass
        elif isinstance(val, six.text_type):
            val = val.encode('utf-8')
        ......

but , In get() function, It decoder to unicoder ,only if the six.PY3 is true 
def _recv_value(self, server, flags, rlen):
        rlen += 2  # include \r\n
        buf = server.recv(rlen)
        if len(buf) != rlen:
            raise _Error("received %d bytes when expecting %d"
                         % (len(buf), rlen))

        if len(buf) == rlen:
            buf = buf[:-2]  # strip \r\n

        if flags & Client._FLAG_COMPRESSED:
            buf = self.decompressor(buf)
            flags &= ~Client._FLAG_COMPRESSED

        if flags == 0:
            # Bare string
            if six.PY3:
                val = buf.decode('utf8')
            else:
                val = buf
        elif flags & Client._FLAG_INTEGER:
            val = int(buf)
       ......

I think we should fix it   like this in set() function

 def _val_to_store_info(self, val, min_compress_len):
        flags = 0
        if isinstance(val, six.binary_type):
            pass
        elif isinstance(val, six.text_type) and six.PY3:
            val = val.encode('utf-8')
        ......

**Comment by timgraham** [comment]
Is it #79 or #80?

**Comment by dsully** [comment]
Fix is in #74 - but still not merge-able. There are no versions of python-memcached that work with Python 3 storing bytes.

**Comment by timgraham** [comment]
Fixed in e1f72daabc011b83a8debb86e9e2b7ff6307a41c, hopefully.
