### ISSUE TITLE
12 Test failures while running tests 

### ISSUE THREAD

**Issue by snehlatamohite** [linsomniac/python-memcached#122]
Hi,

I am trying to build package on ubuntu 16.04 for ppc64le architecture. I am getting 12 test failures having some assertion error. 

I have attached the logs. 

Please help to resolve the issue. 

Thanks,
Snehlata Mohite.
[test_failures.txt](https://github.com/linsomniac/python-memcached/files/1074607/test_failures.txt)

**Comment by timgraham** [comment]
It looks like there's a connection issue to the memcahced server (inet:127.0.0.1:11211: connect: [Errno 111] Connection refused.  Marking dead.).
