### ISSUE TITLE
Python 3.3 Flake8 Failure

### ISSUE THREAD

**Issue by matteius** [linsomniac/python-memcached#129]
It seems all recent Pull Requests are failing on Python 3.3 due to a Flake8 error.   Example:  https://travis-ci.org/linsomniac/python-memcached/builds/272217875?utm_source=github_status&utm_medium=notification

**Comment by hugovk** [comment]
One option is to drop support for Python 3.3, as it's no longer supported after 2017-09-29:

https://en.wikipedia.org/wiki/CPython#Version_history

See https://github.com/linsomniac/python-memcached/pull/116.

**Comment by hugovk** [comment]
Here's the pip installs for python-memcached from PyPI for the last month, virtually zero 3.3 👍 
```
$ pypinfo --percent --pip python-memcached pyversion
python_version percent download_count
-------------- ------- --------------
2.7              89.8%        252,151
3.5               3.9%         10,918
3.6               3.4%          9,431
3.4               1.6%          4,487
2.6               1.3%          3,527
3.3               0.0%            129
3.7               0.0%             10
None              0.0%              7
3.2               0.0%              2

```

**Comment by timgraham** [comment]
Python 3.3 testing removed in 3d08c5e4703652d88ce8f1f79a32a8b8d91c2510.
