### ISSUE TITLE
Support for KEY_PREFIX

### ISSUE THREAD

**Issue by imaia** [linsomniac/python-memcached#138]
Got myself one of these today, using memcached with django1.11:
`TypeError: __init__() got an unexpected keyword argument 'KEY_PREFIX'`

Are there plans to support key_prefix?

**Comment by timgraham** [comment]
This is incorrect Django usage. You should put `'KEY_PREFIX'` in the top-level `CACHES` dictionary, not in `OPTIONS`. For example:
```
CACHES = {
    'memcached': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'KEY_PREFIX': 'memcached',
    },
}
```
