### ISSUE TITLE
Add support to TLS

### ISSUE THREAD

**Issue by moisesguimaraes** [linsomniac/python-memcached#171]
Since version 1.5.13, Memcached [supports TLS][1].

### Motivation

At [OpenStack][2], we use python-memcached in our [oslo.cache][3] Memcache backend driver. To accommodate to some cloud security requirements, we will need to enable TLS in Memcached as data must be encrypted in the wire in some scenarios.

I looked over the documentation and couldn't find anything related to TLS support. If there is a way to achieve that, please let us know.

I would like to help with the implementation of this if needed.

[1]: https://github.com/memcached/memcached/wiki/TLS
[2]: https://www.openstack.org/
[3]: https://opendev.org/openstack/oslo.cache

**Comment by linsomniac** [comment]
I'm sure the offer of help has passed.  I'd be open to accepting fixes that implement it, but it's not something I'm going to be able to work on.  It looks like pymemcache supports TLS, so that's probably the way to go.
