### ISSUE TITLE
SyntaxWarnings with Python 3.8

### ISSUE THREAD

**Issue by tlc28** [linsomniac/python-memcached#176]
Hi,

I've recently updated to Python 3.8 and python-memcached now emits 2 syntax warnings:

```
memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```

Would be great if you could fix this… and publish a patch-version on pypi!

Best regards

**Comment by pablondrina** [comment]
Same here!

**Comment by JaredOzzy** [comment]
Also Getting this issue.

**Comment by tirkarthi** [comment]
I have created https://github.com/linsomniac/python-memcached/pull/178 to fix this

**Comment by tlc28** [comment]
Thanks @tirkarthi !

**Comment by random1st** [comment]
Is there anybody who can merge it?

**Comment by victorelec14** [comment]
The same problem.

**Comment by cclauss** [comment]
Was this fixed?  Can it be closed?

**Comment by linsomniac** [comment]
I agree with @cclauss that this has been resolved, closing.
