### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Cabalist** [linsomniac/python-memcached#177]
Hey there,

The last commit on this project was 3 years ago.   Does anyone know of a maintained/modern version?

**Comment by pope1ni** [comment]
Yes. See #95. I'd recommend checking out [pymemcache](https://pypi.org/project/pymemcache) instead. I recently put in some effort to make sure that it is largely compatible with this abandoned library - for the majority of cases it should now be a drop in replacement.

**Comment by linsomniac** [comment]
Thank you for the pointer to pymemcache.
