### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [linsomniac/python-memcached#188]
Hello all, hello @linsomniac,

it has been a while since the last release (2017).
Python 3.7, 3.8, 3.9, 3.10, 3.11 are now supported (not the case in the last release).

Would it be possible to make a new release of `python-memcached` ?  or is there a reason not to do it now (WIP ?) ?

Thank you and regards  🙏

**Comment by linsomniac** [comment]
Merry Christmas.

**Comment by laulaz** [comment]
Thank you @linsomniac 🎄

**Comment by felixfontein** [comment]
Just a quick comment: the changelog says `Sun, 24 Dec 2024 22:33:47 -0700` - it should say 2023, not 2024 :-)

Merry Christmas to you all as well!

**Comment by linsomniac** [comment]
Good catch, @felixfontein , I'm going to push out a 1.61 that has the corrected date, just to avoid confusion.
