### ISSUE TITLE
New release with python 3 support

### ISSUE THREAD

**Issue by jamielennox** [linsomniac/python-memcached#48]
Hi, 

The latest release is now over a year old and doesn't include any of the python 3 compatibility. Can you release a new version please?

**Comment by haypo** [comment]
Hi,

I wrote a pull request to finish the python-memcached port to Python 3:
linsomniac/python-memcached#67

Please test it!

python-memcached 1.54 released one month ago contains first python 3 fixes, but according to my tests, they are not enough. See my pull request for more information.

Victor

**Comment by linsomniac** [comment]
These have been pulled in and release.  Thanks!

**Comment by haypo** [comment]
The version is 1.56 (released the 2015-07-26).
