### ISSUE TITLE
Google code style formatted docstrings

### ISSUE THREAD

**Issue by gmr** [linsomniac/python-memcached#53]
I'd like to update the codebase to use Google's coding style for docstrings:

```
Args:
    path (str): The path of the file to wrap
    field_storage (FileStorage): The :class:`FileStorage` instance to wrap
    temporary (bool): Whether or not to delete the file when the File
       instance is destructed

Returns:
    BufferedFileStorage: A buffered writable file descriptor
```

Doing so would enable it to work with [Sphinx](http://sphinx-doc.org/) using the [Napoleon extension](http://sphinx-doc.org/latest/ext/napoleon.html>), but did not want to put forth the work if it would not be accepted.

Would you be willing to accept such a pull-request if it is clean, doesn't break anything, etc? I could also add a docs dir with sphinx autodoc so a readthedocs.org site could be setup.

**Comment by linsomniac** [comment]
No response, closing.
