### ISSUE TITLE
1.54 release?

### ISSUE THREAD

**Issue by skimbrel** [linsomniac/python-memcached#64]
Looks like a lot of work has been done since 1.53 — what's the status on a new release?

**Comment by ionelmc** [comment]
The current PyPI release is borken :cry: :
```
  Downloading python-memcached-1.53.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-emd3c1xd/python-memcached/setup.py", line 4, in <module>
        import memcache
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-emd3c1xd/python-memcached/setup.py", line 4, in <module>

        import memcache

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-emd3c1xd/python-memcached

```

**Comment by dhui** [comment]
Was able to install 1.53 via pip, but am wondering when 1.54 will be available on PyPi.
Looks like there's another issue that's also curious about a 1.54 release:
https://github.com/linsomniac/python-memcached/issues/58

**Comment by linsomniac** [comment]
Please try now.  I had marked it for release, but got interrupted before I completed the release process and have been distracted.

**Comment by dhui** [comment]
Thanks! Was able to successfully install/upgrade 1.54
