### ISSUE TITLE
Python 3 TypeError: 'str' does not support the buffer interface - memcache.py line 65

### ISSUE THREAD

**Issue by coreycb** [linsomniac/python-memcached#70]
If memcached isn't running Python3 gets the following error on set():  TypeError: 'str' does not support the buffer interface.  Should this be handled better?

We're hitting this in python-keystoneclient test code that checks if memcached is available.  See: https://github.com/openstack/python-keystoneclient/blob/master/keystoneclient/tests/unit/test_auth_token_middleware.py#L78

Here's the difference between python 2 and 3 behavior:

ubuntu@w1:~$ sudo service memcached stop                                                              
ubuntu@w1:~$ python
Python 2.7.10 (default, Jun  1 2015, 16:21:46) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>>> import memcache
\>>> c = memcache.Client(['localhost:11211'])
\>>> c.set('ping', 'pong', time=1)
0
\>>> quit()
ubuntu@w1:~$ python3
Python 3.4.3+ (default, Jun  2 2015, 14:09:35) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import memcache                                                                                   
\>>> c = memcache.Client(['localhost:11211'])                                                          
\>>> c.set('ping', 'pong', time=1)                                                                     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/memcache.py", line 700, in set
    return self._set("set", key, val, time, min_compress_len, noreply)
  File "/usr/lib/python3/dist-packages/memcache.py", line 983, in _set
    server, key = self._get_server(key)
  File "/usr/lib/python3/dist-packages/memcache.py", line 413, in _get_server
    serverhash = serverHashFunction(str(serverhash) + str(i))
  File "/usr/lib/python3/dist-packages/memcache.py", line 65, in cmemcache_hash
    (((binascii.crc32(key) & 0xffffffff)
TypeError: 'str' does not support the buffer interface
\>>> quit()

**Comment by sergio97** [comment]
In python2 'ping' is an ascii string but in python3 'ping' is a unicode string, which can't be hashed by crc32(). python-memcache does not (sadly) support python3 yet. There's an open Pull Request for this written by Haypo: https://github.com/linsomniac/python-memcached/pull/67

**Comment by coreycb** [comment]
In discussing this with sergio97, this will be fixed in pull request #67 if/when it lands.

**Comment by linsomniac** [comment]
#67 has landed, fixed?

**Comment by thenikso** [comment]
This is still broken for me with v1.57 and python 3. this line https://github.com/linsomniac/python-memcached/pull/67/files#diff-894c02c873c7b32549152655db8797a8R65 should not have been changed

**Comment by furins** [comment]
@thenikso I can confirm that 1.57 is broken with regard to this issue. The latest PRs solve the problem (at least to my installation) so I forced `pip` to load from latest github commit on master 

    pip install --upgrade -e git+https://github.com/linsomniac/python-memcached.git#egg=python-memcached

**Comment by corpulent** [comment]
@thenikso 1.57 doesnt work for me neither.  Installing from master like you suggested worked.
