### ISSUE TITLE
Setting/Getting boolean values yields a ValueError

### ISSUE THREAD

**Issue by papachoco** [linsomniac/python-memcached#75]
In Python Memcached 1.56 (w/ six-1.9.0 & Python 2.7.10)

doing

cache.set('foo', False)
cache.get('foo')

generates a ValueError: invalid literal for int() with base 10: 'False'

line 1235 memcache.py

When the method _val_to_store_info is called the path code that it is followed with a boolean is

       elif isinstance(val, int):
            flags |= Client._FLAG_INTEGER
            val = str(val)
            if six.PY3:
                val = val.encode('ascii')
            # force no attempt to compress this silly string.
            min_compress_len = 0

Since the flags bits have been set to an integer, the boolean value is changed to a string ('False'). So in the method _recv_value the code tries to change that string to an int which fails .

In Python Memcached 1.54

the original code in _val_to_store_info is

elif isinstance(val, int):
            flags |= Client._FLAG_INTEGER
            val = "%d" % val
            # force no attempt to compress this silly string.
            min_compress_len = 0

the issue also affect when checking for long values

**Comment by nicholasserra** [comment]
Also seeing this. We're rolling back our servers to 1.53 until a fix is in. Sounds like this situation needs some test coverage. Not sure if a fix in in progress, will look and contribute if I can.

**Comment by papachoco** [comment]
We rollbacked to  1.54 .. it works fine

**Comment by caiofbpa** [comment]
We tried to rollback, but the `memcache.py` file that gets put into the `python_packages` root doesn't get overwritten by the rollback, causing the issue to persist.

We adapted our code to always use 1 and 0 instead of True and False until this is properly fixed.

I wonder why `memcache.py` is in the `python_packages` root in the first place.

**Comment by caiofbpa** [comment]
Update: I cannot really rollback to an earlier version (1.54 or 1.53). [Pip index](https://pypi.python.org/pypi/python-memcached) shows only version 1.56 as available. When I run `pip install python-memcached==1.53` pip installs version 1.56 instead, with no warnings. Maybe pip index is corrupted?

**Comment by nicholasserra** [comment]
Pip is weird. I had to clear all pip caches and install 1.54 before it would actually give me the correct version.

**Comment by linsomniac** [comment]
I've committed a fix for this, which is to revert it to using "val = '%d'%val", which will do the cast of a boolean into an integer, as it always had.  The section for long values doesn't seem to be impacted in the same way.

**Comment by papachoco** [comment]
thanks a lot

**Comment by nicholasserra** [comment]
Yes, thanks for the quick response.
