### ISSUE TITLE
Is it possible to reformat Changelog according to the best practices proposed by keepachangelog.com?

### ISSUE THREAD

**Issue by svetlyak40wt** [linsomniac/python-memcached#90]
It will be easier to track what happened between two versions if information will be grouped by version.

I could reformat the Changelog file and make a pull-request if you wish.

**Comment by svetlyak40wt** [comment]
So?

**Comment by svetlyak40wt** [comment]
Guys?

**Comment by timgraham** [comment]
I'm not sure what you're proposing. https://github.com/linsomniac/python-memcached/blob/master/ChangeLog looks grouped by version to me.
