### ISSUE TITLE
Package is unmaintained - recommend using pylibmc instead

### ISSUE THREAD

**Issue by edmorley** [linsomniac/python-memcached#94]
In case anyone about to start using python-memcached sees this.

This package is not actively maintained at the moment. For example with the latest release there is a 400% performance slowdown under Python 2.7 (#71) that would be fixed by the unmerged #86.

As such for now I'd strongly recommend using pylibmc instead, which in most cases is a drop-in replacement:
https://github.com/lericson/pylibmc
http://sendapatch.se/projects/pylibmc/misc.html#differences-from-python-memcached

**Comment by linsomniac** [comment]
Thanks for raising this issue.

Please see issue #95 for discussion about future maintenance.

**Comment by edmorley** [comment]
That sounds great - thank you :-)
